server:
  port: 12306
  servlet:
      session:
        timeout: 60m
  undertow:
    threads:
      io: 1
      worker: 4
    url-charset: UTF-8
spring:
    banner:
      charset: UTF-8
    application:
        name: WindowsRemoteAdmin
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      encoding: UTF-8 #编码
      suffix: .html #模板后缀
      mode: HTML #模板
    mvc:
      static-path-pattern: /static/**
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
aes:
    secret-key: WRA12306
logging:
  config: classpath:log4j2-spring-dev.xml